server:
  port: 8080

spring:
  application:
    name: road-cutting-permission-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rcp_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration

rcp:
  rates:
    config-path: classpath:rates-config.json
  workflow:
    config-path: classpath:workflow-config.json
  review-ref: "K7Q2"
  max-search-limit: 50
  default-search-limit: 20
